server:
  port: 1234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeeactivitytracker
    username: root
    password: Sara123$
  jpa:
    hibernate:
      ddl-auto: update # Disable automatic schema generation
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    dialect: org.hibernate.dialect.MySQL8Dialect
  aop:
    proxy-target-class: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pbtjava@gmail.com
    password: jcnsrxqjifkrvqxl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false

